### ISSUE TITLE
Amazing plugin!!

### ISSUE THREAD

**Issue by nchanged** [alex-klock/ng2-fused#2]
Hi!
Wanted to say how amazing this plugin is. Could you update it to the latest fusebox version?
We are about to release 2.0 - a major release with many changes. And your plugins works like a charm.

It should be a part of ng2-example.

http://fuse-box.org:3333/

That's the full config I personally tested with `2.0.0-beta.19`

```js
const {
    FuseBox,
    SassPlugin,
    CSSPlugin,
    WebIndexPlugin,
    TypeScriptHelpers,
    JSONPlugin,
    HTMLPlugin,
    UglifyJSPlugin,
    RawPlugin
} = require('fuse-box');
const { Ng2TemplatePlugin } = require('ng2-fused');

const path = require("path");

const fuse = FuseBox.init({
    homeDir: `src/`,
    output: `dist/$name.js`,
    plugins: [
        WebIndexPlugin({
            title: "FuseBox + Angular",
            template: "src/angular/index.html"
        }),
        // https://github.com/alex-klock/ng2-fused
        Ng2TemplatePlugin(),

        // styles
        ['angular/main.scss', SassPlugin(), CSSPlugin()],
        ['angular/components/todo/**.scss', SassPlugin(), RawPlugin()],
        
        // etc
        JSONPlugin(),
        HTMLPlugin({ useDefault: false })
    ]
});

// setup development sever
fuse.dev({ port: 3000 });

// bundle vendor
fuse.bundle("vendor")
    .hmr()
    .instructions("~ angular/main.ts")

// bundle application
fuse.bundle("app")
    .sourceMaps(true)
    .instructions(" !> [angular/main.ts]").watch().hmr()


// run the factory
fuse.run();
```

Thanks a million!

**Comment by alex-klock** [comment]
Thanks! :) 

Sure thing, I'll get the version updated tonight!

**Comment by nchanged** [comment]
Also, you might be interested in this part: http://fuse-box.org:3333/page/code-splitting
a full fledged code splitting ;-)

**Comment by alex-klock** [comment]
I'll have to update Ng2RouterPlugin to use the new lazyLoad from fuse-tools, that definitely will simplify the output that its doing right now. :)  #3 issue opened to handle that.

**Comment by alex-klock** [comment]
ng2-fused now using fuse-box 2.0
