### ISSUE TITLE
SCSS conversion flow

### ISSUE THREAD

**Issue by patrickmichalina** [alex-klock/ng2-fused#5]
Is is possible convert .scss to css then use this plugin? I would like to maintain the .css in the angular app stylesUrl, but can't seem to figure it out yet. FuseBox is awesome so far, but need to know if a few things can work before moving larger apps to this build tooling.

**Comment by alex-klock** [comment]
It should be possible, I'm currently using PostCSS but the concept should be the same:

```
plugins: [
    Ng2TemplatePlugin(),
    ['*.component.scss', SassPlugin(), RawPlugin()],
    ...
]
```
The above (untested, literally just swapped out the PostCSS() from my own project) is only targeting files that ends with .component.scss.  They key is the array syntax to chain them, with a call to RawPlugin() at the end.

Hope that helps! :)

**Comment by patrickmichalina** [comment]
@alex-klock thanks for the reply. I have tried that, but it doesn't work. The reference remains .scss instead of the output .css. Haven't dug deep into the fuse API to understand how it makes these transformations.
