### ISSUE TITLE
Nested lazy loading

### ISSUE THREAD

**Issue by patrickmichalina** [alex-klock/ng2-fused#8]
Does your plugin support nested lazy modules (folder within folder using + syntax)?

**Comment by alex-klock** [comment]
It doesn't with 0.5 but I've been meaning to experiment with nested lazy modules so guess 0.5.1 is as good as a time as any. :)

**Comment by alex-klock** [comment]
Nested lazy modules now supported with version 0.5.1.

Also added link to your fusebox-angular-universal-starter in the readme.

**Comment by patrickmichalina** [comment]
@alex-klock awesome, now I gotta migrate to your lazy plugin.... the only issue is... in my lazy plugin, I am able to cache bust via hashing the file contents. Is this possible with your plugin?

**Comment by alex-klock** [comment]
Currently the plugin isn't doing that... I think the major difference right now is that it doesn't automatically set the splitConfig (though it does work with whatever you configure so it automatically grabs path values from fusebox) and the name of the entry of the split is the +folderName (minus the +).  Also the start of the build automatically starts with a fresh fushbox cache...

I ran into an issue when switching from AOT or JIT builds (tested 4 different builds... JIT, JIT+Quantum, AOT, AOT+Quantum) with the fusebox cache when HMR was enabled (maybe this is where I need to implement your cache bust strategy). So when a build first starts I just have a task that deletes the fusebox cache for now as a work around.  I'll take a look at what you had done to see if that fixes the cache issue I was running into.
